name: Run Zsh Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Zsh script
      run: |
            chmod +x checkEdge.zsh
            ./checkEdge.zsh > version.json

    - name: Commit and push changes to main
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add version.json
        git commit -m "Update version.json with script output"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Checkout gh-pages branch
      run: |
        git fetch origin
        git checkout gh-pages
      
    - name: Copy version.json to gh-pages
      run: |
        cp version.json version.json
      
    - name: Commit and push changes to gh-pages
      run: |
        git add version.json
        git commit -m "Update version.json with script output"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
